name: Deploy Frontend

on:
  workflow_run:
    workflows: [CI Frontend]
    types: [completed]
    branches: [main]

env:
  PROJECT_DIR: frontend/portfolio-2025
  AWS_REGION: ${{ vars.AWS_REGION }}
  S3_BUCKET: ${{ vars.S3_BUCKET }}
  CF_DIST_ID: ${{ vars.CF_DIST_ID }}
  ROLE_TO_ASSUME: ${{ secrets.ROLE_TO_ASSUME_FRONTEND }}
  VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL}}
  VITE_USE_MOCK: ${{ vars.VITE_USE_MOCK }}
  NODE_VERSION: 22

permissions:
  id-token: write
  contents: read
  actions: read # needed to read artifacts from another run

concurrency:
  group: deploy-frontend-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  deploy:
    if: >
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.event == 'push'
      }}
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4

      # - name: Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: ${{ env.NODE_VERSION }}
      #     cache: "npm"
      #     cache-dependency-path: ${{ env.PROJECT_DIR }}/package-lock.json

      # - name: Install dependencies
      #   run: npm ci
      #   working-directory: ${{ env.PROJECT_DIR }}

      # - name: Build
      #   run: npm run build
      #   working-directory: ${{ env.PROJECT_DIR }}
      #   env:
      #     VITE_API_BASE_URL: ${{ env.VITE_API_BASE_URL }}
      #     VITE_USE_MOCK: ${{ env.VITE_USE_MOCK }}

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: gha-${{ github.ref_name }}-${{ github.run_id }}
      - name: Dump workflow_run payload
        run: |
          echo "=== GITHUB_EVENT_PATH ==="
          echo "$GITHUB_EVENT_PATH"
          echo "=== workflow_run summary ==="
          jq '.workflow_run | {id, name, event, status, conclusion, head_branch, head_sha, url}' < "$GITHUB_EVENT_PATH"

      - name: Download tested artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: ${{ env.PROJECT_DIR }}/dist
          run-id: ${{ github.event.workflow_run.id }}

        # Long-cache all non-HTML assets
      - name: Sync assets (long cache)
        run: |
          aws s3 sync $PROJECT_DIR/dist s3://$S3_BUCKET \
            --delete \
            --exclude "*.html" \
            --cache-control "public,max-age=31536000,immutable"

        # No-store HTML so clients fetch fresh
      - name: Sync HTML (no-store)
        run: |
          aws s3 sync $PROJECT_DIR/dist s3://$S3_BUCKET \
            --delete \
            --exclude "*" --include "*.html" \
            --cache-control "no-store"

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CF_DIST_ID \
            --paths "/index.html" "/"
